import 'package:demo202/models/painting.dart';

class Data {
  static List<Painting> getPaintings() {
    return [
      Painting(
        name: 'Ben Kenobi',
        imageName: 'benkenobi',
        bio: 'Obi-Wan Kenobi was a Force-sensitive human male and a legendary Jedi Master and member of the Jedi High Council during the Fall of the Republic. During the Age of the Empire, he went by the alias of Ben Kenobi in order to hide from the regime that drove the Jedi to near extinction in the aftermath of the Clone Wars. A noble man known for his skills with the Force, Kenobi trained Anakin Skywalker as his Padawan, served as a Jedi General in the Grand Army of the Republic, and became a mentor to Luke Skywalker prior to his death in 0 BBY.\n\n' +
            'Born on the planet Stewjon in 57 BBY, Kenobi was inducted into the Jedi Order at a young age and became the apprentice of Qui-Gon Jinn after completing his initial lessons under Grand Master Yoda. During the Invasion of Naboo in 32 BBY, Kenobi defeated the Sith Lord Darth Maul and was awarded the status of Jedi Knight. Kenobi also began training Anakin Skywalker, having promised his dying master that the boy would become a Jedi, but often had to rein in his adventure-seeking apprentice. Over the years, Kenobi became concerned that Skywalker\'s powers made him arrogant but also regarded him as a good friend and a brother, and ultimately believed that Skywalker was in fact the Chosen One destined to restore balance to the Force by destroying the Sith.\n\n' +
            'When the Clone Wars began in 22 BBY, the Jedi rallied to defend the Galactic Republic against the Confederacy of Independent Systems, and Kenobi became a general in the newly-formed Republic Military. Kenobi and Skywalker often served alongside each other, leading their respective clone trooper divisions, the 212th Attack Battalion, and the 501st Legion, against the Separatist Droid Army. However, in 19 BBY, Skywalker fell to the dark side of the Force due to the manipulation of Darth Sidious, embracing his new identity as the Sith Lord Darth Vader and playing a crucial role in the near-extermination of the Jedi Order. Kenobi, who was betrayed by his soldiers as a result of Order 66, confronted his fallen apprentice on Mustafar. The ensuing lightsaber duel between the former friends concluded when Vader was maimed at the hands of his one-time master, who withdrew into exile with Skywalker\'s newborn son.\n\n' +
            'For two decades Kenobi lived as a hermit on the planet Tatooine, located in the Outer Rim Territories, hiding from the Galactic Empire that replaced the Republic. When Princess Leia Organa beseeched him to join their Rebel cause in 0 BBY, Kenobi was prepared to join the Alliance to Restore the Republic and also decided that the time had come for Luke Skywalker to become a Jedi like his father before him. However, their journey to Alderaan became a rescue operation upon discovering that the princess had been taken as a prisoner to the Death Star. While attempting to help his allies escape from the battle station, Kenobi encountered Vader, now rebuilt as a cyborg and forced to rely on an armored suit with life support technology in order to survive. Though he initially defended himself, Kenobi ultimately sacrificed himself, allowing Vader to strike him down as the Rebels fled on the Millennium Falcon. Yet death was not the end of Obi-Wan Kenobi, having learned to preserve his identity in the Force, Kenobi became a Force spirit and was therefore able to continue guiding Luke on the path to Jedi Knighthood.',
      ),
      Painting(
        name: 'Boba Fett',
        imageName: 'BobaFett',
        bio: 'Boba Fett was a clone of Jango Fett, the human male bounty hunter whose genetic code spawned an army of clone troopers during the final years of the Galactic Republic. With his customized Mandalorian armor, deadly weaponry, and the fearsome Slave I as his starship, Boba carried on his "father\'s" legacy by becoming one of the most feared bounty hunters in the galaxy, during the reign of the Galactic Empire. Trained in combat and martial skills from a young age, he became a legend over the course of his career, which included contracts for the Empire and the criminal underworld.\n\n' +
            'When Jango Fett was hired by the Sith Lord Darth Tyranus, agreeing to become the template for the Grand Army of the Republic, he requested an unaltered clone that he could raise as a son. That "son" was Boba Fett; unlike the clone troopers, all of whom were modified through programming and growth acceleration, Boba was an example of pure genetic replication. Raised on the extragalactic planet Kamino, Boba and Jango were confronted by the Jedi Knight Obi-Wan Kenobi, whose arrival forced the Fetts to rendezvous with Tyranus on Geonosis in 22 BBY. During the initial phase of the Battle of Geonosis, Boba witnessed Jango\'s death at the hands of Jedi Master Mace Windu, whose swift decapitation of the infamous mercenary resulted in Boba developing a lifelong hatred of all Jedi.\n\n' +
            'The orphaned Fett grew up in the company of criminals during the Clone Wars. He joined the crew of Aurra Sing, hoping the ruthless bounty hunter would help him exact revenge against Windu. Their plot ultimately ended in failure, leading to a brief stint in prison after which Fett struck out on his own, working as a bounty hunter alongside the likes of Bossk and Dengar. Over the years, Fett was employed as a mercenary by crime lords as well as the Sith. During the Galactic Civil War, he successfully tracked the Millennium Falcon to Bespin for the Sith Lord Darth Vader, who allowed the bounty hunter to take Captain Han Solo to the Hutt gangster Jabba Desilijic Tiure in 3 ABY. A year later, the Alliance to Restore the Republic attempted to rescue Solo on Tatooine, where they fought against the Hutt\'s mercenaries, including Fett, above the Great Pit of Carkoon. During the battle, Solo accidentally slammed a pole into Fett\'s jetpack, igniting it and causing the bounty hunter to tumble into the man-eating sarlacc pit.',
      ),
      Painting(
        name: 'Chewie',
        imageName: 'chewie',
        bio: 'Chewbacca, known affectionately to his friends as Chewie, was a Wookiee warrior, smuggler, and resistance fighter who fought in the Clone Wars, the Galactic Civil War, and the conflict between the First Order and the Resistance. He hailed from the planet Kashyyyk and became a Wookiee military leader. During the Clone Wars, he was captured by Trandoshan slavers and held captive on Wasskah, but he worked with a fellow captive, Jedi Commander Ahsoka Tano, to escape. He later commanded Wookiee forces during the Battle of Kashyyyk alongside the Grand Army of the Republic, led by Jedi Master Yoda. During the battle, one of the last ones of the war, Yoda\'s clone troopers received Order 66 from Supreme Chancellor Palpatine and, with the help of Chewbacca and his fellow Wookiee Tarfful, Yoda escaped Kashyyyk and the destruction of the Jedi Order.\n\n' +
            'In the years that followed, during the rule of the Galactic Empire, Chewbacca became a smuggler and the co-pilot of Captain Han Solo aboard the Millennium Falcon. They worked in the employ of crime lord Jabba Desilijic Tiure until Solo was forced to dump a shipment of spice to avoid trouble with the Empire, at which point a bounty was placed on their heads. Soon thereafter, Chewbacca and Solo were hired by Jedi Master Obi-Wan Kenobi to ferry him, Luke Skywalker, C-3PO, and R2-D2 to Alderaan on a mission vital to the survival of the Alliance to Restore the Republic. After finding Alderaan was destroyed, the group was brought aboard the Death Star, where they helped Princess Leia Organa escape from captivity and return to the Rebel base on Yavin 4. Though Chewbacca and Solo initially chose to leave Yavin 4 and not join the Rebellion, they ended up fighting in the Battle of Yavin and were instrumental in Skywalker\'s destruction of the Death Star, a major victory for the Rebellion.\n\n' +
            'Throughout the war, Chewbacca and Solo fought the Empire in a number of engagements, including an assault on Cymoon 1 and the battle on Vrogas Vas. Along with Princess Organa and C-3PO, they escaped from Echo Base on the planet Hoth after the Empire tracked the Rebel Alliance there. The group sought refuge with Lando Calrissian, an old friend of Solo\'s, on Cloud City, but Calrissian betrayed them and turned them over to Darth Vader, the Emperor\'s chief enforcer, after his city was threatened. Solo was frozen in carbonite and Calrissian helped the others escape, but they were too late to save the frozen Solo from being taken by Boba Fett to Jabba the Hutt. Chewbacca and Calrissian set off to find Solo and located him in Jabba\'s Palace on Tatooine, where Chewbacca and his friends saved Solo and destroyed Jabba. Shortly thereafter, they fought in the Battle of Endor, where Chewbacca helped destroy the shield generator and allowed the Alliance Fleet to destroy the DS-2 Death Star. The Emperor was killed aboard the battle station, delivering a crippling blow to the Empire.\n\n' +
            'After Endor and the rise of the New Republic, Chewbacca and Solo fought to liberate Kashyyyk from the Empire. When the war finally came to a close, Chewbacca returned home to Kashyyyk with his family. After Solo\'s son Ben, turned to the dark side and destroyed Skywalker\'s new generation of Jedi, Chewbacca reunited with his old friend and the two spent many years as smugglers once more. They lost the Millennium Falcon and ended up smuggling aboard a ship called the Eravana, but they eventually found the Falcon and, with it, stowaways named Rey, Finn, and the droid BB-8. The droid had part of a map that led to the exiled Luke Skywalker, so the group brought the map to the Resistance that opposed the First Order, which had risen from the ashes of the Galactic Empire. Chewbacca soon fought in the assault to destroy Starkiller Base, a devastating First Order superweapon, a conflict in which Solo lost his life at the hands of his son. After the base was destroyed, Chewbacca joined Rey in traveling to the planet Ahch-To on the Falcon, where they found Luke Skywalker. After Solo\'s death, Chewbacca often served as the sole pilot of the Falcon, including piloting the ship to aid the Resistance during the Battle of Crait.\n\n'
                'Roughly a year after the battle of Crait, Chewbacca was one of the last of the Resistance. Having learned of the mysterious return of the Emperor, Chewbacca and the crew of the Falcon, now including Poe Dameron, traveled to the planets Pasaana and Kijimi to find a clue to how to find where the Emperor was hiding, being reunited with his friend Calrissian in the process. The quest nearly ended in Chewie\'s death, as Rey, having been revealed to be the ancient phantom menace\'s granddaughter through his son, lashed out with dark power during a fight with Kylo Ren and destroyed a First Order transport that she had thought Chewie had been loaded onto, seemingly killing him.\n\n' +
            'However, Chewie survived and was rescued by the Resistance as they continued the quest. Rey eventually found Exegol during a failed self-exile attempt to protect the galaxy from her becoming a Sith, and led the charge during the battle that ensued later on. Rey ultimately killed her malevolent grandfather with the help of the returned Ben Solo in the climax of the battle, while the Resistance, joined by the galaxy fleet, progressively overpowered the Sith fleet of essential Death Stars that the Emperor planned to unleash.\n\n' +
            'Having destroyed the Sith once and for all, the Resistance reveled in their victory, but also mourned their losses, including Leia, who had died of natural causes shortly after reaching out to her son and helping him turn back towards the light. Chewie was presumably not present on his beloved ship when Rey took it and BB-8 to bury the Skywalker lightsaber and Leia\'s own at the site of Luke\'s former home on Tatooine.',
      ),
      Painting(
        name: 'Han Solo',
        imageName: 'hanSolo',
        bio: 'Han Solo was a male Human smuggler from the planet Corellia who achieved galactic fame as a member of the Rebel Alliance and later the New Republic. Born on Corellia, he was orphaned at an early age and taken by the pirate Garris Shrike to serve on his crew. He was treated cruelly, and served Shrike for many years before escaping while in his teens. Solo became a smuggler, and fell in love with Bria Tharen, though she left him due to her duties to the Rebel Alliance. Solo then entered the Imperial Academy at Carida, serving with distinction. He was kicked out, however, when he stopped an Imperial officer from beating a Wookiee named Chewbacca with a neuronic whip for resisting capture. In gratitude, the Wookiee swore a life debt to Solo, protecting him with his life and a bond of friendship formed between the two that was unbreakable. Solo became a smuggler once again, with Chewbacca at his side. Piloting the upgraded and customized the Millennium Falcon, which he won in a game of Sabacc against Lando Calrissian, his future ally, he became known as one of the best smugglers in the galaxy.\n\n' +
            'On the run from Imperial officials, Solo became caught up with the Rebel Alliance, courtesy of Obi-Wan Kenobi, Luke Skywalker, and Princess Leia Organa, whom he helped rescue from the Death Star. Solo helped Skywalker destroy the Death Star when it attacked the Rebel base at Yavin 4, where they had taken Organa. Solo became an unofficial member of the Rebel Alliance, and fell in love with Organa. He officially joined the Alliance in 4 ABY and was immediately commissioned as a general. He led the strike team that helped destroy the Second Death Star at the Battle of Endor, in which Emperor Palpatine was killed. A year later, the New Republic was founded.\n\n' +
            'Solo married Organa in 8 ABY, and the two had three children: Jaina, Jacen, and Anakin. As the New Republic was threatened by many enemies in its first years of existence, Solo was always on the move, sometimes traveling with Skywalker, who was Organa\'s brother. Along with his wife and faithful Wookiee friend, Solo fought against Warlord Zsinj, Grand Admiral Thrawn, the reborn Emperor Palpatine, Admiral Daala and the Yevetha. In 25 ABY the New Republic was attacked by the Yuuzhan Vong. The war that followed lasted four years and was extremely bloody. Solo\'s closest friend Chewbacca and his son Anakin Solo both died during the war, deaths that haunted the ex-smuggler. The Vong were eventually defeated and the New Republic was reformed into the Galactic Alliance. In 40 ABY, his son Jacen turned to the dark side of the Force, and took control of the Galactic Alliance. Solo and his wife joined the rebel faction opposing Darth Caedus, and the two were prepared to kill him, as they no longer saw him as their son. At the end of the war, Solo was still having tense relations with the GA government.',
      ),
      Painting(
        name: 'Princess Leia',
        imageName: 'leia',
        bio: 'Leia Organa Solo (born Leia Amidala Skywalker), a Force-sensitive Human female was at various stages of her life, a politician, revolutionary, and Jedi Knight of the New Jedi Order. The daughter of Jedi Knight Anakin Skywalker and Senator Padmé Amidala of Naboo, Leia was the younger twin sister of Luke Skywalker, and, shortly after her birth, she became the adopted daughter of Bail Organa and Queen Breha of Alderaan, making her a Princess of Alderaan. An accomplished Senator, Leia Organa was most famous for her strong leadership during the Galactic Civil War and other subsequent galactic conflicts, making her one of the galaxy\'s greatest heroes. Later she married Han Solo, and became the mother of their three children: Jaina, Jacen, and Anakin Solo. Around the start of the Swarm War, Leia unknowingly became a grandmother through Jacen\'s daughter Allana.\n\n' +
            'She had a forceful personality and bright intellect, having accomplished much in her youth: she was a strong proponent for the Rebel Alliance, the youngest Senator ever of the Galactic Empire at eighteen standard years of age, and a member of the Royal Family of Alderaan. Years later, she was instrumental in the creation of the New Republic, and was elected to the position of Chief of State, serving twice in that office.\n\n' +
            'Due to her powerful Force heritage, Leia, following her family\'s legacy, became a Jedi Knight in the New Jedi Order. She was partially trained by her brother Luke and later by Jedi Master Saba Sebatyne, who declared her a fully trained Knight at the end of the Swarm War. This training would serve her well as the galaxy teetered on the edge of collapse into civil war once more during the Second Galactic Civil War, although it complicated her allegiance. During this conflict, Leia\'s son Jacen turned to the dark side of the Force, becoming the Sith Lord Darth Caedus. Leia and Han became determined to destroy Caedus, feeling that their son was already dead. However, it was their daughter Jaina who ended his life in a lightsaber duel that also concluded the war.\n\n' +
            'In the aftermath of Caedus\' death, the Solos became the guardians of their granddaughter Allana, at the behest of her mother, Tenel Ka of Hapes, and remained two of the galaxy\'s most important figures, standing with the Jedi Order amidst the tensions that arose between it and the government of Chief of State Natasi Daala.',
      ),
      Painting(
        name: 'Biggie',
        imageName: 'biggie',
        bio: 'Christopher George Latore Wallace (May 21, 1972 – March 9, 1997), widely known by his stage name The Notorious B.I.G., or, more commonly among the familiar, Biggie Smalls or simply Biggie, was an American rapper, in the New York and gangsta rap traditions, who ranks among the greatest rappers ever. With a lyrical delivery laidback and yet slick, belying the lyrics\' often grim content and his own intimidating appearance, his songs were often semi-autobiographical, telling of hardship and criminality, but also of debauchery and celebration.\n\n' +
            'Born and raised in Brooklyn, New York City, Wallace signed to Sean "Puffy" Combs\' label Bad Boy Records as it launched in 1993, and gained exposure through features on several, other artists\' singles that year. His debut album, Ready to Die, released in 1994, now his magnum opus, made him the central figure in East Coast hip hop, and restored New York\'s visibility at a time when gangster rapper Snoop Dogg, of the Los Angeles rap scene, was dominating the rap genre. The following year, Biggie led his protégé group Junior M.A.F.I.A., a team of himself and longtime friends, including Lil\' Kim, to chart success.\n\n' +
            'During 1996, while recording his second album, Biggie became ensnarled in the escalating East Coast–West Coast hip hop feud. Following Tupac Shakur\'s death in a drive-by shooting in Las Vegas in September 1996, speculations of involvement by criminal elements orbiting the Bad Boy circle circulated. On March 9, 1997, while visiting Los Angeles, Wallace was murdered in a drive-by shooting. The assailant remains unidentified. Biggie\'s second album, Life After Death, double length, was released two weeks later. It reached #1 on the Billboard 200, and became a rare rap album attaining Diamond sales, 10 million copies sold.\n\n' +
            'With three more posthumous albums released, The Notorious B.I.G. has accrued certified sales of over 28 million copies in the United States, including 21 million albums. Rolling Stone has called him the "greatest rapper that ever lived," and Billboard named him as the greatest rapper of all time. In 2020, The Notorious B.I.G. was inducted into the Rock and Roll Hall of Fame.',
      ),
      Painting(
        name: 'Anthony Hopkins',
        imageName: 'anthony_hopkins',
        bio: 'Sir Philip Anthony Hopkins CBE (born 31 December 1937) is a Welsh actor, director and film producer. He won the Academy Award for Best Actor in 1992 and has also received three BAFTAs, two Emmys and the Cecil B. DeMille Award. In 1993, he was knighted by Queen Elizabeth II for services to the arts. Hopkins received a star on the Hollywood Walk of Fame in 2003, and in 2008 he received the BAFTA Fellowship for lifetime achievement from the British Academy of Film and Television Arts.\n\n' +
            'After graduating from the Royal Welsh College of Music & Drama in 1957, he trained at the Royal Academy of Dramatic Art in London, and was then spotted by Laurence Olivier who invited him to join the Royal National Theatre in 1965. Productions at the National included King Lear, his favourite Shakespeare play. Despite his success in theatre, Hopkins yearned to be on screen. His last stage play was a West End production of M. Butterfly in 1989.\n\n' +
            'In 1968, Hopkins achieved renown in film, playing Richard the Lionheart in The Lion in Winter. In the mid-1970s, Richard Attenborough, who would direct five Hopkins films, called him "the greatest actor of his generation." In 1991 he portrayed Hannibal Lecter in The Silence of the Lambs, for which he won the Academy Award for Best Actor. He reprised the role in its sequel Hannibal and the prequel Red Dragon. Hopkins was nominated for four other Academy Awards for the films, The Remains of the Day (1993), Nixon (1995), Amistad (1997) and The Two Popes (2019). Other notable films include: 84 Charing Cross Road (1987), The Elephant Man (1980), Howards End (1992), Bram Stoker\'s Dracula (1992), Legends of the Fall (1994), Meet Joe Black (1998), The Mask of Zorro (1998), as well as Thor (2011) and its 2013 and 2017 sequels. In 2015, he starred in the BBC television film The Dresser, a role he called "the highlight of my life." In 2016 and 2018, he starred in the HBO television series Westworld.',
      ),
      Painting(
        name: 'Charlize Theron',
        imageName: 'charlize_theron',
        bio: 'Charlize Theron (/ʃɑːrˈliːz ˈθɛrən/ shar-LEEZ THERR-ən; Afrikaans: [ʃarˈlis ˈtrɔn]; born 7 August 1975) is a South African and American actress and producer. She is the recipient of several accolades, including an Academy Award, a Golden Globe Award, an American Cinematheque Award, and the Silver Bear for Best Actress. Time magazine named her one of the 100 most influential people in the world in 2016, and she is one of the world\'s highest-paid actresses, as of 2019.\n\n' +
            'Theron came to international prominence in the 1990s by playing the leading lady in the Hollywood films The Devil\'s Advocate (1997), Mighty Joe Young (1998), and The Cider House Rules (1999). In 2003, she received critical acclaim for her portrayal of serial killer Aileen Wuornos in Monster, for which she won the Academy Award for Best Actress, becoming the first South African to win an Oscar in an acting category. She received another Academy Award nomination for playing a sexually abused woman seeking justice in the drama North Country (2005). Theron has since starred in several top-grossing action films, including Hancock (2008), Snow White and the Huntsman (2012), Prometheus (2012), Mad Max: Fury Road (2015), The Fate of the Furious (2017), and Atomic Blonde (2017). She also received praise for playing troubled women in Jason Reitman\'s comedy-dramas Young Adult (2011) and Tully (2018), and for portraying Megyn Kelly in the drama Bombshell (2019), receiving a third Academy Award nomination for Best Actress.\n\n' +
            'Since the early 2000s, Theron has ventured into film production with her company Denver and Delilah Productions. She has produced numerous films, in many of which she had a starring role, including The Burning Plain (2008), Dark Places (2015), and Long Shot (2019). Theron became an American citizen in 2007, while retaining her South African citizenship.',
      ),
      Painting(
        name: 'The Cat',
        imageName: 'cat',
        bio: 'Cats is a 2019 musical fantasy film based on the stage musical of the same name by Andrew Lloyd Webber, which in turn was based on the poetry collection Old Possum\'s Book of Practical Cats (1939) by T. S. Eliot. The film is directed by Tom Hooper—in his second feature musical following Les Misérables (2012)—from a screenplay by Lee Hall and Hooper and features an ensemble cast, including James Corden, Judi Dench, Jason Derulo, Idris Elba, Jennifer Hudson, Ian McKellen, Taylor Swift, Rebel Wilson, and Francesca Hayward.\n\n' +
            'Cats was theatrically released in the United Kingdom and the United States on 20 December 2019, by Universal Pictures. The film received generally unfavourable reviews from critics, who criticized the CGI effects, plot, and tone, with many calling it one of the worst films of 2019. The film also became a box-office bomb, grossing \$76 million on a budget as high as \$100 million.',
      ),
      Painting(
        name: 'Prince',
        imageName: 'Prince',
        bio: 'Prince Rogers Nelson (June 7, 1958 – April 21, 2016) was an American singer, songwriter, musician, record producer, dancer, actor, and filmmaker. A guitar virtuoso and multi-instrumentalist known for his genre-crossing work, flamboyant stage appearances and wide-ranging singing voice, in particular his far reaching falsetto and high pitched screams, he is regarded as one of the greatest, versatile and most successful musicians in the history of popular music. better source needed] His innovative music integrated a wide variety of styles, including funk, R&B, rock, new wave, soul, psychedelia, and pop. Prince pioneered the late 1970s Minneapolis sound, a funk rock subgenre drawing from synth-pop and new wave.\n\n' +
            'Born and raised in Minneapolis, Prince developed an interest in music as a young child and wrote his first song, "Funk Machine", at the age of seven. He signed a recording contract with Warner Bros. Records at the age of 19, and released his debut album For You in 1978. Following up with his next four albums—Prince (1979), Dirty Mind (1980), Controversy (1981), and 1999 (1982)—Prince gained critical success, prominently showcasing his explicit lyrics as well as his blending of funk, dance, and rock music. In 1984, he began referring to his backup band as The Revolution and released his sixth album Purple Rain, which was also the soundtrack to his hugely successful film acting debut of the same name. It quickly became his most commercially successful record, spending 24 consecutive weeks atop the Billboard 200. The film itself was critically and commercially successful and also won the Academy Award for Best Original Song Score, the last film to receive the award.\n\n' +
            'Following the disbandment of The Revolution, Prince released the critically acclaimed double album Sign o\' the Times (1987). He released three more solo albums—Lovesexy (1988), the Batman soundtrack (1989), and the Graffiti Bridge soundtrack (1990)—before debuting his New Power Generation backing band in 1991. In the midst of a contractual dispute with Warner Bros. in 1993, Prince changed his stage name to the unpronounceable symbol Logo. Hollow circle above downward arrow crossed with a curlicued horn-shaped symbol and then a short bar, known to fans as the "Love Symbol", and began releasing new albums at a faster rate in order to quickly meet his contract quota and release himself from further obligations to the record label. He released five records between 1994 and 1996 before he signed with Arista Records in 1998. He began referring to himself as "Prince" again in 2000 and subsequently released 16 albums, including Musicology (2004), his most successful album of that decade. His final album, Hit n Run Phase Two, was first released on the Tidal streaming service in 2015.\n\n' +
            'In April 2016, at the age of 57, Prince died of an accidental fentanyl overdose at his Paisley Park home and recording studio in Chanhassen, Minnesota. He sold over 100 million records worldwide, ranking him among the best-selling music artists of all time. He won seven Grammy Awards, seven Brit Awards, six American Music Awards, four MTV Video Music Awards, an Academy Award, and a Golden Globe Award. He was also honored with special awards including the Grammy President\'s Merit Award, American Music Awards for Achievement and of Merit, and the Billboard Icon Award. He was inducted into the Rock and Roll Hall of Fame in 2004, the UK Music Hall of Fame in 2006, and the Rhythm and Blues Music Hall of Fame in 2016. In 2016, he was posthumously honored with a Doctor of Humane Letters by the University of Minnesota. Rolling Stone placed him among its list of the 100 Greatest Artists of All Time.',
      ),
      Painting(
        name: 'Kurt Russell',
        imageName: 'kurt_Russel',
        bio: 'Kurt Vogel Russell (born March 17, 1951) is an American actor. He began acting on television at the age of 12 in the western series The Travels of Jaimie McPheeters (1963–1964). In the late 1960s, he signed a ten-year contract with The Walt Disney Company where, according to Robert Osborne, he became the studio\'s top star of the 1970s.\n\n' +
            'Russell was nominated for a Golden Globe Award for Best Supporting Actor – Motion Picture for his performance in Silkwood (1983). In the 1980s, he starred in several films directed by John Carpenter, including anti-hero roles such as army hero-turned-robber Snake Plissken in the futuristic action film Escape from New York (1981), and its sequel Escape from L.A. (1996), helicopter pilot R.J. MacReady in the remake of the horror film The Thing (1982), and truck driver Jack Burton in the dark kung-fu comedy action film Big Trouble in Little China (1986), all of which have since become cult films. He was nominated for an Emmy Award for the television film Elvis (1979), also directed by Carpenter.\n\n' +
            'Russell starred in other films, including Overboard (1987), Tango & Cash (1989), Backdraft (1991) Tombstone (1993), Stargate (1994), Miracle (2004), Sky High (2005), Death Proof (2007), The Hateful Eight (2015), Guardians of the Galaxy Vol. 2 (2017) and Once Upon a Time in Hollywood (2019). He also appeared in The Fast and the Furious franchise, having starred in Furious 7 (2015) and The Fate of the Furious (2017).',
      ),
      Painting(
        name: 'Tyrion Lannister ',
        imageName: 'Tyrion',
        bio: 'Tyrion Lannister is the youngest son of Joanna Lannister and Lord Tywin Lannister. Tywin was the head of House Lannister, the richest man in the Seven Kingdoms and Lord Paramount of the Westerlands. The Westerlands are one of the constituent regions of the Seven Kingdoms and House Lannister of Casterly Rock is one of the Great Houses of the realm. He is the younger brother of Jaime and Cersei Lannister. His mother Joanna Lannister died giving birth to him. His father and sister blame Tyrion for the death.\n\n' +
            'He is a dwarf, causing him problems and persecution. His size has led him to being referred to derisively by various names, such as "The Imp" and "The Halfman". This is mitigated by his intellect and his family\'s wealth and power. Had an infant with dwarfism like Tyrion been born a commoner, he\'d have simply been left out in the woods to die. However, Tyrion was born into a powerful noble House, and was therefore spared. Even though his father doesn\'t think much of him, he has had the benefits of being raised with wealth and education, and is expected to lead his life as a credit to the Lannister name. He is committed to the good of both his House, and since Cersei married King Robert Baratheon, his family\'s continued hold on the throne.\n\n' +
            'When Tyrion was 16, he met a wheelwright\'s daughter named Tysha on the road, apparently the victim of an attempted rape. While his brother Jaime ran off the attackers, Tyrion helped Tysha recover from the ordeal, and they became lovers. They found a drunken, wandering septon willing to marry them and briefly, they lived as husband and wife. However, Lord Tywin learned what had happened and became displeased. Jaime confessed that he organized the incident to make his brother happy, and Tysha was actually a prostitute. As a lesson, Tywin gave Tysha to his guards, paying her a silver coin for each man and forcing Tyrion to watch. By the end, there were so many silver coins that they were running out of her hands onto the ground. Tyrion has reciprocated Tywin\'s hatred ever since.\n\n' +
            'His two siblings had positions of respect and responsibility since their teens. When Tyrion turned sixteen (the age of manhood), Tywin Lannister put Tyrion in charge of the drains and cisterns at Casterly Rock. Tyrion brags that the "[sewage] never flowed [smoother] to the sea."\n\n' +
            'Fandom may earn an affiliate commission on sales made from links on this page.\n\n' +
            'Tyrion once encountered Lord Gregor Forrester at the tourney in Lannisport. While they once spoke briefly, Tyrion found Gregor very honorable, even mentioning it to Gregor\'s daughter Mira years later.\n\n' +
            'Tyrion spent a lot of time at court in King\'s Landing to avoid his father. He got on well with Jaime and his niece Myrcella and nephew Tommen, but had a colder relationship with Cersei and his sadistic nephew Joffrey. He has a fondness for prostitutes and drink, but is also intelligent, cunning, and educated. He is also a kind man who would protect the innocent, claiming that he loves broken things.',
      ),
      Painting(
        name: 'Wonder Woman',
        imageName: 'WonderWoman',
        bio: 'Wonder Woman is a fictional superhero appearing in American comic books published by DC Comics. The character is a founding member of the Justice League. The character first appeared in All Star Comics #8 in October 1941 with her first feature in Sensation Comics #1 in January 1942. The Wonder Woman title has been published by DC Comics almost continuously except for a brief hiatus in 1986. In her homeland, the island nation of Themyscira, her official title is Princess Diana of Themyscira. When blending into the society outside of her homeland, she sometimes adopts her civilian identity Diana Prince.\n\n' +
            'Wonder Woman was created by the American psychologist and writer William Moulton Marston (pen name: Charles Moulton), and artist Harry G. Peter. Marston\'s wife, Elizabeth, and their life partner, Olive Byrne, are credited as being his inspiration for the character\'s appearance. Marston\'s comics featured his ideas on DISC theory, and the character drew a great deal of inspiration from early feminists, and especially from birth control pioneer Margaret Sanger; in particular, her piece "Woman and the New Race".\n\n' +
            'Wonder Woman\'s origin story relates that she was sculpted from clay by her mother Queen Hippolyta and was given a life to live as an Amazon, along with superhuman powers as gifts by the Greek gods. In recent years, DC changed her background with the retcon that she is the daughter of Zeus and Hippolyta, jointly raised by her mother and her aunts Antiope and Menalippe. The character has changed in depiction over the decades, including briefly losing her powers entirely in the late 1960s; by the 1980s, artist George Perez gave her an athletic look and emphasized her Amazonian heritage. She possesses an arsenal of advanced technology, including the Lasso of Truth, a pair of indestructible bracelets, a tiara which serves as a projectile, and, in older stories, a range of devices based on Amazon technology.\n\n' +
            'Wonder Woman\'s character was created during World War II; the character in the story was initially depicted fighting Axis military forces as well as an assortment of colorful supervillains, although over time her stories came to place greater emphasis on characters, deities, and monsters from Greek mythology. Many stories depicted Wonder Woman rescuing herself from bondage, which defeated the "damsels in distress" trope that was common in comics during the 1940s. In the decades since her debut, Wonder Woman has gained a cast of enemies bent on eliminating the Amazon, including classic villains such as Ares, Cheetah, Doctor Poison, Circe, Doctor Psycho, and Giganta, along with more recent adversaries such as Veronica Cale and the First Born. Wonder Woman has also regularly appeared in comic books featuring the superhero teams Justice Society (from 1941) and Justice League (from 1960).\n\n' +
            'The character is a well-known figure in popular culture that has been adapted to various media. October 21 is Wonder Woman Day, commemorating the release of her first appearance in All Star Comics #8 (with the exception of 2017 which held the day on June 3 to tie in with the release of the film of the same name).\n\n' +
            'Wonder Woman has been featured in various media from radio to television and film, and appears in merchandise sold around the world, such as apparel, toys, dolls, jewelry, and video games. Shannon Farnon, Susan Eisenberg, Maggie Q, Lucy Lawless, Keri Russell, Michelle Monaghan, Rosario Dawson, Cobie Smulders, and Halsey among others, have provided the character\'s voice for animated adaptations. Wonder Woman has been depicted in both film and television by Cathy Lee Crosby, Lynda Carter, and in the DC Extended Universe films by Gal Gadot.',
      ),
      Painting(
        name: 'Arya Stark',
        imageName: 'arya',
        bio: 'Arya Stark is the youngest daughter and third child of Lady Catelyn and Lord Ned Stark.\n\n' +
            'Arya was born and raised at Winterfell. She has an older sister, Sansa, an older brother Robb, two younger brothers Bran and Rickon Stark, and a "bastard half-brother" Jon Snow.\n\n' +
            'Arya rejects the notion that she must become a lady and marry for influence and power. Instead, she believes that she can forge her own destiny. She is fascinated by warfare and training in the use of arms, and is bored by embroidery and other "lady-like" pursuits. She takes after her father and has a quarrelsome relationship with her sister Sansa, due to their contrasting interests and personalities. She is close to her "half-brother" Jon, who is also something of an outsider.',
      )
    ];
  }
}
